// Demo data for guest mode. Mirrors the shape of real Supabase rows so every view
// (Recipes, Stats, Meal Prep, Recipe Detail) works unmodified against it.
// Nothing here is ever written back to a database — guest mode is entirely in-memory.

const day = (offset) => {
  const d = new Date()
  d.setDate(d.getDate() - offset)
  return d.toISOString().slice(0, 10)
}

export const DEMO_RECIPES = [
  {
    id: 'demo-cleaner', title: 'All purpose cleaner', tagline: 'Mandarin infused',
    category: 'Household', subcategory: null, servings: null, total_minutes: null,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'orange peels (or any citrus peel, lemons work too)', unit: 'cups', amount: 2 },
      { id: 'i2', name: 'white vinegar', unit: 'cups', amount: 3 },
      { id: 'i3', name: 'Handful of cloves (about 10)', unit: null, amount: null },
      { id: 'i4', name: 'Fresh rosemary sprigs', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Place the orange peels into your jar. Add rosemary or cloves for extra scent. Cover completely with vinegar.', timer_seconds: null },
      { id: 's2', content: 'Seal the jar and store in a cool, dark place for 1-2 weeks to let the citrus oils infuse.', timer_seconds: null },
      { id: 's3', content: 'After 1-2 weeks, strain the liquid to remove peels and any debris.', timer_seconds: null },
      { id: 's4', content: 'Optional: add 5-10 drops of your favorite essential oil. Shake gently to mix.', timer_seconds: null },
      { id: 's5', content: 'Dilute roughly 1-1 with water. Transfer the vinegar solution into a clean spray bottle halfway, then top off with water.', timer_seconds: null },
    ] }, { group: 'How to Use', items: [
      { id: 's6', content: 'Spray directly onto most non-porous surfaces (countertops, stainless steel, bathroom tiles). Avoid natural stone or unfinished wood.', timer_seconds: null },
      { id: 's7', content: 'Wipe clean with a cotton cloth or reusable rag.', timer_seconds: null },
    ] }],
    variants: [], notes: 'The infused vinegar concentrate lasts indefinitely if strained well. Once diluted, use within 2-3 months. Store in a cool, dark place.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313975935.png',
    calories: null, protein_g: null, carbs_g: null, fat_g: null, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(130),
  },
  {
    id: 'demo-baobuns', title: 'Bao buns - gochujangbloemkool', tagline: 'Van deze fluffy broodjes blijf je dooreten',
    category: 'Sides', subcategory: null, servings: 4, total_minutes: 60,
    ingredients: [
      { group: 'Bao buns zelf maken', items: [
        { id: 'i1', name: 'zelfrijzend bakmeel', unit: 'g', amount: 250 },
        { id: 'i2', name: 'zout', unit: 'tl', amount: 1 },
        { id: 'i3', name: 'bakpoeder', unit: 'tl', amount: 1 },
        { id: 'i4', name: 'halfvolle melk', unit: 'ml', amount: 200 },
        { id: 'i5', name: 'sesamolie', unit: 'el', amount: 2 },
      ] },
      { group: 'Vulling', items: [
        { id: 'i6', name: 'bloemkoolkrop', unit: null, amount: 1 },
        { id: 'i7', name: 'botersla', unit: null, amount: null },
        { id: 'i8', name: 'gochujang', unit: 'el', amount: 0.5 },
        { id: 'i9', name: 'agavesiroop', unit: 'el', amount: 1 },
        { id: 'i10', name: 'sesamzaad', unit: 'el', amount: 1 },
        { id: 'i11', name: 'Kewpie mayonaise', unit: null, amount: null },
        { id: 'i12', name: 'wat maizena', unit: null, amount: null },
        { id: 'i13', name: 'knoflookpoeder', unit: null, amount: null },
        { id: 'i14', name: 'sojasaus', unit: null, amount: null },
      ] },
    ],
    steps: [
      { group: 'Bao buns', items: [
        { id: 's1', content: 'Meng het zelfrijzend bakmeel, zout, bakpoeder en de melk in een kom. Roer tot een samenhangend deeg ontstaat.', timer_seconds: null },
        { id: 's2', content: 'Kneed het deeg met bebloemde handen ongeveer 5 minuten tot een soepel deeg.', timer_seconds: 300 },
        { id: 's3', content: 'Verdeel het deeg in 12 gelijke balletjes. Rol elk balletje uit tot een ovaal van ±12 cm lang en 6 cm breed. Bestrijk dun met sesamolie en vouw dubbel.', timer_seconds: null },
        { id: 's4', content: 'Breng een laag water van 4 cm aan de kook met een stoommand erboven. Stoom de buns afgedekt in 10 minuten gaar.', timer_seconds: 600 },
      ] },
      { group: 'Vulling', items: [
        { id: 's5', content: 'Verwarm de oven voor op 200°C en snij de bloemkool in roosjes. Meng met maizena, water, knoflookpoeder, olie en zout. Rooster 20 minuten in de oven.', timer_seconds: 1200 },
        { id: 's6', content: 'Meng 0.5 el gochujang met 1.5 el sojasaus en 1.5 el agavesiroop. Meng met de bloemkool en nog 10 minuten in de oven.', timer_seconds: 600 },
      ] },
      { group: 'Laatste stappen', items: [
        { id: 's7', content: 'Open de broodjes, beleg met sla, gochujangbloemkool en japanse mayonaise naar smaak.', timer_seconds: null },
      ] },
    ],
    variants: [], notes: 'Make-ahead/freeze: Steamed buns freeze very well — freeze plain (unfilled) buns after steaming, then re-steam straight from frozen for 8-10 minutes. The roasted gochujang bloemkool also freezes well; assemble fresh.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782677290001.webp',
    calories: 773, protein_g: 4.2, carbs_g: 17.1, fat_g: 78.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(30),
  },
  {
    id: 'demo-birriataco', title: 'Beef Birria tacos', tagline: 'Crunchy, cheesy slow-cooked beef',
    category: 'Main dishes', subcategory: 'Tacos, wraps & nachos', servings: 6, total_minutes: 300,
    ingredients: [
      { group: 'Birria tacos', items: [
        { id: 'i1', name: 'ancho peppers', unit: null, amount: 3 },
        { id: 'i2', name: 'guajillo peppers', unit: null, amount: 6 },
        { id: 'i3', name: 'oaxacan melting cheese', unit: null, amount: null },
        { id: 'i4', name: 'schenkel', unit: 'kg', amount: 1 },
        { id: 'i5', name: 'rundvlees short rib', unit: 'kg', amount: 1 },
        { id: 'i6', name: 'knoflook', unit: 'teen', amount: 4 },
        { id: 'i7', name: 'mais tortillas', unit: null, amount: null },
        { id: 'i8', name: 'witte azijn', unit: 'cup', amount: 0.5 },
        { id: 'i9', name: 'kaneelstokje', unit: null, amount: 1 },
        { id: 'i10', name: 'oregano', unit: 'tl', amount: 1 },
        { id: 'i11', name: 'komijnzaad', unit: 'tl', amount: 0.5 },
        { id: 'i12', name: 'grote geroosterde tomaten', unit: null, amount: 2 },
      ] },
      { group: 'Green salsa', items: [
        { id: 'i13', name: 'tomatillos', unit: null, amount: 2 },
        { id: 'i14', name: 'serrano peppers', unit: null, amount: 4 },
        { id: 'i15', name: 'garlic cloves', unit: null, amount: 3 },
        { id: 'i16', name: 'juice from 1 lime', unit: null, amount: null },
        { id: 'i17', name: 'handful of cilantro', unit: null, amount: null },
      ] },
      { group: 'Red salsa', items: [
        { id: 'i18', name: 'roma tomatoes', unit: null, amount: 2 },
        { id: 'i19', name: 'arbol peppers', unit: null, amount: 8 },
        { id: 'i20', name: 'garlic cloves', unit: null, amount: 4 },
      ] },
    ],
    steps: [
      { group: 'The night before', items: [
        { id: 's1', content: 'Season the meat with salt and pepper, then place in a large baking dish. Slightly toast the peppers over medium heat. Soak peppers in hot water for 20 minutes. Roast the onion and garlic.', timer_seconds: null },
        { id: 's2', content: 'Toast the whole cloves, cumin seeds, and black peppercorns. Blend with roasted tomatoes, herbs, onion, cinnamon and vinegar.', timer_seconds: null },
        { id: 's3', content: 'Once peppers are soft, drain, add to the blender and puree until smooth. Pour the sauce over the meat. Cover and refrigerate overnight or at least 4 hours.', timer_seconds: null },
      ] },
      { group: 'Day of', items: [
        { id: 's4', content: 'Preheat the oven to 175°C. Bake the meat covered with foil for about 4 hours or until fork tender.', timer_seconds: null },
        { id: 's5', content: 'Make the green salsa by blending all green salsa ingredients. For red salsa: broil tomatoes and onion until charred, then blend with arbol peppers and garlic.', timer_seconds: null },
        { id: 's6', content: 'Dip tortillas in the consomé, place on a hot skillet, sprinkle with cheese and beef and cook until crunchy. Serve with consomé to dip and both salsas.', timer_seconds: null },
      ] },
    ],
    variants: [], notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312573322.jpg',
    calories: 3791, protein_g: 312.8, carbs_g: 217.3, fat_g: 194.6, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(55),
  },
  {
    id: 'demo-bluelagoon', title: 'Blue Lagoon', tagline: 'Voor de smurfentong',
    category: 'Drinks', subcategory: 'Cocktails', servings: 1, total_minutes: 5,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'sprite/7up', unit: 'ml', amount: 90 },
      { id: 'i2', name: 'wodka', unit: 'ml', amount: 30 },
      { id: 'i3', name: 'blue curaçao', unit: 'ml', amount: 15 },
      { id: 'i4', name: 'ijsklontjes', unit: null, amount: null },
      { id: 'i5', name: 'limoen/citroen voor garnering', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Vul je glas met ijsklontjes.', timer_seconds: null },
      { id: 's2', content: 'Voeg per glas 30 ml wodka en 15 ml blue curaçao toe.', timer_seconds: null },
      { id: 's3', content: 'Vul het overige gedeelte met sprite tot het glas vol is (ongeveer 90 ml).', timer_seconds: null },
      { id: 's4', content: 'Snijd een limoen in plakjes en zet op het glas voor garnering.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Verhouding wodka:blue curaçao:sprite = 2:1:6.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313728937.jpg',
    calories: null, protein_g: null, carbs_g: null, fat_g: null, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: ['Cold Meal'], created_at: day(110),
  },
  {
    id: 'demo-bruschetta', title: 'Bruschetta', tagline: 'Italiaans recept',
    category: 'Appetizers & Snacks', subcategory: null, servings: 2, total_minutes: 15,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'sneetjes stokbrood', unit: null, amount: 4 },
      { id: 'i2', name: 'rijpe tomaten', unit: null, amount: 4 },
      { id: 'i3', name: 'knoflook, doormidden gesneden', unit: 'teen', amount: 1 },
      { id: 'i4', name: 'paar takjes basilicum', unit: null, amount: null },
      { id: 'i5', name: 'extra vergine olijfolie', unit: 'el', amount: 1 },
      { id: 'i6', name: 'peper en zout', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Rooster of gril de sneetjes stokbrood tot goudbruin. Als ze nog warm zijn, wrijf je ze even in met de doorgesneden knoflook.', timer_seconds: null },
      { id: 's2', content: 'Snijd de tomaat in kleine stukjes. Hak de basilicum in dunne reepjes. Voeg de tomaat, basilicum, zout, peper en olijfolie samen in een kom en hussel goed door elkaar.', timer_seconds: null },
      { id: 's3', content: 'Beleg de gegrilde sneetjes stokbrood met het tomatenmengsel.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Tomato topping keeps 2 days in the fridge (add basil just before serving). Toasted bread keeps 2 days at room temp or freezes up to a month — store separately from the topping.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313943629.jpg',
    calories: 669, protein_g: 18.3, carbs_g: 99.3, fat_g: 21.4, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(120),
  },
  {
    id: 'demo-caprese', title: 'Caprese salade', tagline: 'Altijd goed ernaast',
    category: 'Salads', subcategory: null, servings: 2, total_minutes: 10,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'cherrytomaten aan de tak', unit: 'g', amount: 250 },
      { id: 'i2', name: 'verse basilicum', unit: 'g', amount: 15 },
      { id: 'i3', name: 'mini mozzarella bolletjes', unit: 'g', amount: 150 },
      { id: 'i4', name: 'olijfolie extra vierge', unit: 'el', amount: 3 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'De tomaatjes haal je van de tak en halveer je. Ook de bolletjes mozzarella snijd je door de helft.', timer_seconds: null },
      { id: 's2', content: 'Meng de tomaatjes en de mozzarella met de olijfolie. De blaadjes basilicum voeg je eraan toe en strooi er eventueel nog een beetje zout en peper overheen.', timer_seconds: null },
      { id: 's3', content: 'Geniet ervan!', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Best assembled just before serving — tomatoes release liquid and basil wilts within a few hours. Not suitable for freezing.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313878085.jpg',
    calories: 818, protein_g: 33.0, carbs_g: 3.0, fat_g: 76.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: ['Cold Meal'], created_at: day(105),
  },
  {
    id: 'demo-carpaccio', title: 'Carpaccio wraps', tagline: 'Gewoon omdat het kan',
    category: 'Breakfast & Brunch', subcategory: null, servings: 4, total_minutes: 15,
    ingredients: [
      { group: null, items: [
        { id: 'i1', name: 'wraps', unit: null, amount: 4 },
        { id: 'i2', name: 'runder carpaccio', unit: 'g', amount: 300 },
        { id: 'i3', name: 'rucola', unit: 'g', amount: 100 },
        { id: 'i4', name: 'mayonaise', unit: 'el', amount: 6 },
        { id: 'i5', name: 'Truffelolie', unit: null, amount: null },
        { id: 'i6', name: 'Parmezaanse kaas', unit: null, amount: null },
      ] },
      { group: 'Optioneel', items: [
        { id: 'i7', name: 'Geroosterde pijnboompitten', unit: null, amount: null },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Rooster de pijnboompitten.', timer_seconds: null },
      { id: 's2', content: 'Voeg wat truffelolie toe aan de mayonaise en roer goed. Smeer het op de wrap.', timer_seconds: null },
      { id: 's3', content: 'Beleg met een dikke laag rucola, de carpaccio, wat kaas en pijnboompitten. Voeg zout en peper toe. Vouw goed dicht.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Best assembled fresh — raw deli carpaccio, mayo and rucola don\'t hold up well in the fridge or freezer once wrapped.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313620703.jpg',
    calories: 1522, protein_g: 43.9, carbs_g: 100.2, fat_g: 104.9, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(70),
  },
  {
    id: 'demo-casserole', title: 'Casserole', tagline: 'One-pot love',
    category: 'Main dishes', subcategory: null, servings: 3, total_minutes: 40,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'Pasta naar keuze', unit: null, amount: null },
      { id: 'i2', name: 'groene pesto', unit: 'pot', amount: 1 },
      { id: 'i3', name: 'knoflook', unit: 'teen', amount: 4 },
      { id: 'i4', name: 'grote ui', unit: null, amount: 1 },
      { id: 'i5', name: 'kipfilet', unit: 'g', amount: 300 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Verwarm de oven voor op 180°C. Kook de pasta volgens de aanwijzingen. Snipper de ui en hak de knoflook fijn.', timer_seconds: null },
      { id: 's2', content: 'Snijd de kipfilet in stukjes en bak samen met de ui en knoflook in een pan tot de kip gaar en lichtbruin is.', timer_seconds: null },
      { id: 's3', content: 'Schep de afgegoten pasta, de gebakken kip en de pesto bij elkaar in een ovenschaal en mix goed door elkaar. Bak 25-30 minuten tot gaar en goudbruin.', timer_seconds: 1800 },
    ] }],
    variants: [], notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313205313.jpg',
    calories: 1484, protein_g: 106.5, carbs_g: 27.8, fat_g: 101.4, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(65),
  },
  {
    id: 'demo-chiliconqueso', title: 'Chili Con Queso', tagline: 'Cheeeeeeeeeeeeese',
    category: 'Sides', subcategory: 'Dips & Snacks', servings: 8, total_minutes: 55,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'spek, in stukjes gesneden en uitgebakken', unit: 'g', amount: 500 },
      { id: 'i2', name: 'smeltkaas, in grote stukken', unit: 'g', amount: 900 },
      { id: 'i3', name: 'gerookte Goudakaas, in blokjes', unit: 'g', amount: 500 },
      { id: 'i4', name: 'tomatenblokjes met groene chilipeper', unit: 'blik', amount: 1 },
      { id: 'i5', name: 'geroosterde tomatenblokjes met groene chilipeper', unit: 'blik', amount: 1 },
      { id: 'i6', name: 'champignonroomsoep', unit: 'blik', amount: 1 },
      { id: 'i7', name: 'koffie-kruidenrub', unit: 'el', amount: 4 },
      { id: 'i8', name: 'verse koriander, fijngehakt', unit: 'ml', amount: 120 },
      { id: 'i9', name: 'tortillachips, voor erbij', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Bak het spek tot het niet meer rauw is. Haal het spek uit de pan.', timer_seconds: null },
      { id: 's2', content: 'Combineer in een ovenvaste pan de smeltkaas en gerookte Goudakaas. Voeg de tomatenblokjes, champignonroomsoep, gebakken spek en kruidenrub toe.', timer_seconds: null },
      { id: 's3', content: 'Verwarm op 175°C en roer 3-4 keer tot de kaas gesmolten is, ongeveer 45 minuten. Voeg het grootste deel van de koriander de laatste 5 minuten toe. Serveer met tortillachips.', timer_seconds: 2700 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Keeps a few days in the fridge and reheats fine. Freezing isn\'t recommended — the cheese can separate and turn grainy.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313259262.jpg',
    calories: 9089, protein_g: 456.5, carbs_g: 54.7, fat_g: 790.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(85),
  },
  {
    id: 'demo-chili', title: 'Chili con Carne', tagline: 'Zonder enge dingen',
    category: 'Main dishes', subcategory: null, servings: 4, total_minutes: 50,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'rode ui, gesnipperd', unit: null, amount: 1 },
      { id: 'i2', name: 'rode paprikas, in stukjes', unit: null, amount: 2 },
      { id: 'i3', name: 'cayennepeper', unit: 'tl', amount: 1 },
      { id: 'i4', name: 'gehakt', unit: 'g', amount: 400 },
      { id: 'i5', name: 'passata', unit: 'ml', amount: 500 },
      { id: 'i6', name: 'witte rijst (of afbak broodjes)', unit: 'g', amount: 350 },
      { id: 'i7', name: 'kidneybonen van 400 g, afgespoeld en uitgelekt', unit: 'blik', amount: 1 },
      { id: 'i8', name: 'pure chocolade, in stukjes', unit: 'g', amount: 20 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Fruit de rode ui en koriandersteeltjes 5 minuten op laag vuur. Roerbak de rode paprika 5 minuten mee.', timer_seconds: null },
      { id: 's2', content: 'Strooi de kruiden erover en bak 1 minuut mee. Schep het gehakt erdoor en bak op hoog vuur snel rul en bruin.', timer_seconds: null },
      { id: 's3', content: 'Giet de passata in de pan en breng aan de kook. Laat 30 minuten zonder deksel pruttelen.', timer_seconds: 1800 },
      { id: 's4', content: 'Kook intussen de witte rijst volgens de aanwijzingen op de verpakking.', timer_seconds: null },
      { id: 's5', content: 'Voeg de kidneybonen en chocolade toe. Geef het nog 10-15 minuten terwijl je af en toe roert.', timer_seconds: 750 },
    ] }],
    variants: [], notes: 'Voor vega: laat het gehakt weg en voeg wat extra bonen toe.\n\nMake-ahead/freeze: Freezes excellently for up to 3 months and often tastes even better the next day.',
    photo_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Chili con carne with beef, beans, chili peppers, garlic, black pepper, and a soft-boiled egg - Massachusetts.jpg',
    calories: 2025, protein_g: 126.3, carbs_g: 208.5, fat_g: 77.3, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(10),
  },
  {
    id: 'demo-rosbief', title: 'Deluxe broodje rosbief', tagline: 'Wanneer wil je dat nu niet',
    category: 'Breakfast & Brunch', subcategory: null, servings: 4, total_minutes: 15,
    ingredients: [
      { group: null, items: [
        { id: 'i1', name: 'stokbroden of 4 triangle broodjes', unit: null, amount: 2 },
        { id: 'i2', name: 'groene pesto', unit: 'pot', amount: 1 },
        { id: 'i3', name: 'rucola', unit: 'zak', amount: 1 },
        { id: 'i4', name: 'rosbief', unit: 'pak', amount: 1 },
        { id: 'i5', name: 'lenteui', unit: null, amount: 1 },
        { id: 'i6', name: 'Zongedroogde tomaatjes', unit: null, amount: null },
        { id: 'i7', name: 'mayonaise', unit: 'el', amount: 1 },
        { id: 'i8', name: 'Olijfolie', unit: null, amount: null },
      ] },
      { group: 'Optioneel', items: [
        { id: 'i9', name: 'Parmezaanse kaas', unit: null, amount: null },
        { id: 'i10', name: 'Geroosterde pijnboompitten', unit: null, amount: null },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Bak het brood af en snijd het open.', timer_seconds: null },
      { id: 's2', content: 'Meng 2 el pesto met 1 el mayonaise en besmeer je brood met een goede laag.', timer_seconds: null },
      { id: 's3', content: 'Verdeel de rucola over je brood en erna de rosbief. Roer 1 el pesto met 2 el olie en druppel over de rosbief.', timer_seconds: null },
      { id: 's4', content: 'Verdeel erna de pijnboompitten, lenteui, reepjes zongedroogde tomaat en parmezaanse kaas over het brood. Bestrooi royaal met peper en zout.', timer_seconds: null },
    ] }],
    variants: [], notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313602637.jpg',
    calories: 1908, protein_g: 32.1, carbs_g: 61.8, fat_g: 170.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(75),
  },
  {
    id: 'demo-flammkuchen', title: 'Flammkuchen', tagline: 'incl. variaties',
    category: 'Main dishes', subcategory: 'Oven dishes', servings: 2, total_minutes: 20,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'Flammkuchen deeg', unit: null, amount: null },
      { id: 'i2', name: 'Crème fraîche', unit: null, amount: null },
      { id: 'i3', name: 'Zout en peper', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Verwarm de oven voor op de hoogste stand.', timer_seconds: null },
      { id: 's2', content: 'Rol het deeg dun uit en besmeer met crème fraîche.', timer_seconds: null },
      { id: 's3', content: 'Beleg met de topping van keuze en bak goudbruin en krokant.', timer_seconds: null },
    ] }],
    variants: [
      { id: 'var-spek', label: 'Spek, ui & geitenkaas', steps: [{ group: 'Bereiding', items: [
        { id: 'sv1', content: 'Verdeel de spekjes, ui en geitenkaas over het beslagen deeg. Bak tot de rand goudbruin en krokant is.', timer_seconds: null },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi1', name: 'Spekjes', unit: null, amount: null },
        { id: 'vi2', name: 'Rode ui, dun gesneden', unit: null, amount: null },
        { id: 'vi3', name: 'Geitenkaas', unit: null, amount: null },
      ] }] },
      { id: 'var-truffel', label: 'Champignon & truffel', steps: [{ group: 'Bereiding', items: [
        { id: 'sv2', content: 'Verdeel de champignons en een beetje truffeltapenade over het deeg. Bestrooi met parmezaanse kaas en bak goudbruin.', timer_seconds: null },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi4', name: 'Champignons, dun gesneden', unit: null, amount: null },
        { id: 'vi5', name: 'Truffeltapenade', unit: null, amount: null },
        { id: 'vi6', name: 'Parmezaanse kaas', unit: null, amount: null },
      ] }] },
    ],
    notes: 'Make-ahead/freeze: Best eaten fresh and crispy straight from the oven. You can prep the toppings ahead though.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312447023.jpg',
    calories: 145, protein_g: 1.0, carbs_g: 1.5, fat_g: 15.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(45),
  },
  {
    id: 'demo-mudslide', title: 'Frozen mudslide', tagline: 'Bonaire in a cup',
    category: 'Drinks', subcategory: 'Cocktails', servings: 2, total_minutes: 10,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'quarts vanilla ice cream', unit: null, amount: 1.5 },
      { id: 'i2', name: 'ounces Irish cream', unit: null, amount: 2 },
      { id: 'i3', name: 'ounces Kahlúa coffee liqueur', unit: null, amount: 2 },
      { id: 'i4', name: 'ounce vodka', unit: null, amount: 1 },
      { id: 'i5', name: 'chocolate syrup, to taste', unit: null, amount: null },
      { id: 'i6', name: 'whipped cream, to taste', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Place the ice cream, Irish cream, Kahlúa, and vodka in a blender. Blend until smooth.', timer_seconds: null },
      { id: 's2', content: 'Drizzle the inside of two glasses with chocolate syrup.', timer_seconds: null },
      { id: 's3', content: 'Add the mudslide mixture to the glasses. Top with whipped cream and more chocolate syrup.', timer_seconds: null },
    ] }],
    variants: [], notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313769839.jpg',
    calories: 1038, protein_g: 7.0, carbs_g: 37.3, fat_g: 96.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: ['Cold Meal'], created_at: day(100),
  },
  {
    id: 'demo-gajinamul', title: 'Gaji-Namul', tagline: 'Korean marinated eggplant banchan',
    category: 'Sides', subcategory: 'Vegetables', servings: 4, total_minutes: 45,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'Japanese eggplant (4-6 eggplants), halved lengthwise', unit: 'g', amount: 910 },
      { id: 'i2', name: 'vegetable oil', unit: 'ml', amount: 60 },
      { id: 'i3', name: 'honey', unit: 'ml', amount: 45 },
      { id: 'i4', name: 'distilled white vinegar', unit: 'ml', amount: 45 },
      { id: 'i5', name: 'toasted sesame oil', unit: 'ml', amount: 45 },
      { id: 'i6', name: 'fish sauce', unit: 'ml', amount: 30 },
      { id: 'i7', name: 'doenjang', unit: 'g', amount: 15 },
      { id: 'i8', name: 'medium garlic cloves, finely chopped', unit: null, amount: 2 },
      { id: 'i9', name: 'toasted sesame seeds', unit: 'g', amount: 30 },
      { id: 'i10', name: 'medium scallions, sliced', unit: null, amount: 2 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Preheat oven to 220°C. Toss eggplant with vegetable oil and salt. Arrange cut side down on baking sheets. Roast until browned and completely tender, 25-30 minutes.', timer_seconds: 1800 },
      { id: 's2', content: 'Whisk together honey, vinegar, sesame oil, fish sauce, doenjang, garlic, and pepper. Stir in sesame seeds.', timer_seconds: null },
      { id: 's3', content: 'Once cool, tear eggplant into ribbons and add to the dressing. Massage for 2-3 minutes until absorbed. Fold in scallions. Refrigerate at least 2 hours before serving.', timer_seconds: 7200 },
    ] }],
    variants: [], notes: 'Can be made in advance and refrigerated in an airtight container for up to 1 week.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313388986.jpg',
    calories: 1443, protein_g: 15.7, carbs_g: 124.9, fat_g: 105.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(88),
  },
  {
    id: 'demo-rundvlees', title: 'Gefrituurd rundvlees', tagline: 'zoet en pittig tegelijk',
    category: 'Main dishes', subcategory: null, servings: 4, total_minutes: 180,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'rundersukadelappen', unit: 'g', amount: 750 },
      { id: 'i2', name: 'citroengras, gekneusd', unit: 'stengel', amount: 2.5 },
      { id: 'i3', name: 'paar blaadjes laurier', unit: null, amount: null },
      { id: 'i4', name: 'cm gember, gekneusd', unit: null, amount: 6 },
      { id: 'i5', name: 'korianderzaad', unit: 'el', amount: 1 },
      { id: 'i6', name: 'amandelschaafsel', unit: null, amount: null },
      { id: 'i7', name: 'sjalotten', unit: null, amount: 4 },
      { id: 'i8', name: 'knoflook', unit: 'teen', amount: 5 },
      { id: 'i9', name: 'rode pepers', unit: null, amount: 2 },
      { id: 'i10', name: 'kokosmelk', unit: 'ml', amount: 600 },
      { id: 'i11', name: 'palmsuiker', unit: 'el', amount: 1 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Breng in een ruime pan de sukadelappen in 1 L water, citroengras, laurierblaadjes en de gember aan de kook. Stoof het vlees in ongeveer 1.5 uur.', timer_seconds: 5400 },
      { id: 's2', content: 'Rooster de peperkorrels, korianderzaad en amandel in een droge pan. Meng fijn met een vijzel, voeg de sjalot, knoflook en pepers toe.', timer_seconds: null },
      { id: 's3', content: 'Verhit in een pan wat olie en fruit deze pasta in ongeveer 5 minuten gaar. Voeg de tamarindepulp, kokosmelk, palmsuiker en zout toe. Zet het vuur laag.', timer_seconds: null },
      { id: 's4', content: 'Na 1.5 uur haal je de sukadelappen uit de pan en stamp ze fijn, voeg het vlees toe aan de pasta en stoof nog 1 uur op laag vuur. Bak daarna in porties goudbruin.', timer_seconds: 3600 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Freezes excellently for up to 3 months. Freeze before the final frying step, then fry fresh portions as needed.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313050094.jpg',
    calories: 3343, protein_g: 210.1, carbs_g: 57.6, fat_g: 271.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(92),
  },
  {
    id: 'demo-hasselback', title: 'Gochujang hasselback potatos', tagline: 'Cheeeeeeeeeeeeese',
    category: 'Sides', subcategory: 'Potatoes', servings: 4, total_minutes: 90,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'medium potatoes, scrubbed', unit: null, amount: 8 },
      { id: 'i2', name: 'butter, softened', unit: 'g', amount: 150 },
      { id: 'i3', name: 'gochujang', unit: 'tbsp', amount: 3 },
      { id: 'i4', name: 'parmesan cheese, finely grated', unit: 'cup', amount: 0.25 },
      { id: 'i5', name: 'garlic cloves, finely chopped', unit: null, amount: 4 },
      { id: 'i6', name: 'finely chopped spring onion', unit: 'cup', amount: 0.25 },
      { id: 'i7', name: 'sea salt', unit: 'tsp', amount: 1 },
      { id: 'i8', name: 'grated mozzarella', unit: 'cups', amount: 1.5 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Use a knife to create hasselback slices about 3mm apart. Place potatoes in a roasting dish. Preheat the oven to 200°C.', timer_seconds: null },
      { id: 's2', content: 'Mix together the butter, gochujang, parmesan, garlic, spring onion and sea salt. Spread over each potato, getting into the cuts. Cover and seal tightly with foil. Roast for 1 hour or until tender.', timer_seconds: 3600 },
      { id: 's3', content: 'Remove the foil. Stuff the sliced potatoes with mozzarella. Return to the oven and roast 15 minutes until the cheese has melted.', timer_seconds: 900 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: You can slice and butter the potatoes a few hours ahead. Not a good freezer dish — potatoes turn grainy when frozen.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313416938.jpg',
    calories: 2918, protein_g: 116.4, carbs_g: 142.1, fat_g: 216.1, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(78),
  },
  {
    id: 'demo-gyoza', title: 'Gyoza', tagline: 'A snack for every event',
    category: 'Sides', subcategory: 'Dips & Snacks', servings: 6, total_minutes: 60,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'wonton wrappers', unit: null, amount: 52 },
      { id: 'i2', name: 'ground turkey', unit: 'lb', amount: 1 },
      { id: 'i3', name: 'cabbage, shredded', unit: 'cup', amount: 2 },
      { id: 'i4', name: 'green onions, chopped', unit: 'cup', amount: 0.5 },
      { id: 'i5', name: 'garlic cloves, pressed', unit: null, amount: 2 },
      { id: 'i6', name: 'sesame oil', unit: 'tbsp', amount: 1 },
      { id: 'i7', name: 'soy sauce', unit: 'tbsp', amount: 1 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'In a large bowl, combine ground turkey with onions, cabbage, pressed garlic, sesame oil, soy sauce and ground black pepper.', timer_seconds: null },
      { id: 's2', content: 'Place an equal portion of filling into each wrapper. Brush the edges with water and seal the filling inside.', timer_seconds: null },
      { id: 's3', content: 'Preheat a skillet over medium-high with oil. Pan fry until golden brown, about 3 minutes. Add water and cover with a lid, steam for 3-4 minutes to cook the filling.', timer_seconds: null },
      { id: 's4', content: 'Serve with your favorite sauce while still warm.', timer_seconds: null },
    ] }],
    variants: [
      { id: 'var-smashed', label: 'Smashed gyoza', steps: [{ group: 'Bereiding', items: [
        { id: 'sv1', content: 'Bereid de vulling zoals in het hoofdrecept. Leg op elk hoopje een gyoza vel en smash met een spatel. Bak kort aan, draai om, voeg olie en water toe en dek af. Laat gaan tot het geluid van stomen overgaat naar bakken.', timer_seconds: null },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi1', name: 'wonton wrappers', unit: null, amount: 52 },
        { id: 'vi2', name: 'ground turkey', unit: 'lb', amount: 1 },
      ] }] },
    ],
    notes: 'Make-ahead/freeze: Uncooked gyoza freeze excellently — freeze flat on a tray until solid, then transfer to a bag (up to 2-3 months). Cook straight from frozen.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313281008.jpg',
    calories: 8216, protein_g: 331.2, carbs_g: 1307.3, fat_g: 175.3, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(62),
  },
  {
    id: 'demo-kimchirice', title: 'Kimchi fried rice', tagline: 'Spicy, korean-style fried rice',
    category: 'Main dishes', subcategory: null, servings: 2, total_minutes: 20,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'kimchi', unit: 'g', amount: 150 },
      { id: 'i2', name: 'butter', unit: 'tbsp', amount: 1 },
      { id: 'i3', name: 'bacon, diced', unit: 'g', amount: 150 },
      { id: 'i4', name: 'onion, finely diced', unit: null, amount: 1 },
      { id: 'i5', name: 'garlic cloves, finely chopped', unit: null, amount: 2 },
      { id: 'i6', name: 'gochujang', unit: 'tbsp', amount: 1 },
      { id: 'i7', name: 'cooked rice', unit: 'cups', amount: 2 },
      { id: 'i8', name: 'soy sauce', unit: 'tbsp', amount: 1 },
      { id: 'i9', name: 'spring onions, finely sliced', unit: null, amount: 2 },
      { id: 'i10', name: 'fried eggs, to serve', unit: null, amount: 2 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Drain the kimchi, reserve the liquid. Stir-fry the kimchi in a hot wok for 2-3 minutes until it starts to char. Transfer to a plate.', timer_seconds: null },
      { id: 's2', content: 'Heat the butter in the wok. Add the bacon and cook 2-3 minutes. Add onion and garlic, cook 2 minutes. Add gochujang and cook 30 seconds.', timer_seconds: null },
      { id: 's3', content: 'Add the rice, roasted kimchi, soy sauce and reserved kimchi liquid. Stir-fry until well combined. Toss through the spring onion. Serve topped with a fried egg.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Day-old refrigerated rice works best.\n\nMake-ahead/freeze: Freezes very well for up to 2 months. Top with a freshly fried egg after reheating.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313077091.jpg',
    calories: 857, protein_g: 27.5, carbs_g: 33.0, fat_g: 69.2, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(58),
  },
  {
    id: 'demo-kipmanchego', title: 'Kip manchego met mangosaus', tagline: 'De snelle versie in de oven',
    category: 'Sides', subcategory: 'Dips & Snacks', servings: 4, total_minutes: 35,
    ingredients: [
      { group: null, items: [
        { id: 'i1', name: 'kipfilet', unit: null, amount: 1 },
        { id: 'i2', name: 'mango', unit: null, amount: 1 },
        { id: 'i3', name: 'manchego kaas', unit: null, amount: null },
        { id: 'i4', name: 'suiker', unit: null, amount: null },
      ] },
      { group: 'Leuk voor erbij', items: [
        { id: 'i5', name: '(Kokos) rijst', unit: null, amount: null },
        { id: 'i6', name: 'Zoete aardappel', unit: null, amount: null },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Kip snijden in 2 delen over de lengte, plat slaan, goed kruiden aan beide kanten.', timer_seconds: null },
      { id: 's2', content: 'Manchego kaas schaven en plakjes op de kip leggen. Kip oprollen en 25 minuten in de oven op 200 graden.', timer_seconds: 1500 },
      { id: 's3', content: 'Mango pureren en warm maken met wat suiker (2-3 eetlepels). Serveer met (kokos) rijst en/of zoete aardappel.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: You can assemble the rolled chicken raw and freeze it up to 2 months. The mango sauce also freezes well separately.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313491937.jpg',
    calories: 570, protein_g: 30.4, carbs_g: 73.2, fat_g: 17.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(82),
  },
  {
    id: 'demo-lasagne', title: 'Lasagne speciaal', tagline: 'Met pompoen, rode biet, mascarpone en geitenkaas',
    category: 'Main dishes', subcategory: 'Oven dishes', servings: 6, total_minutes: 80,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'gekookte rode bieten', unit: 'g', amount: 500 },
      { id: 'i2', name: 'verse salie', unit: 'g', amount: 10 },
      { id: 'i3', name: 'mascarpone', unit: 'g', amount: 200 },
      { id: 'i4', name: 'halfvolle melk', unit: 'ml', amount: 150 },
      { id: 'i5', name: 'lasagne all-uovo', unit: 'g', amount: 250 },
      { id: 'i6', name: 'pompoenlasagnevellen', unit: 'g', amount: 350 },
      { id: 'i7', name: 'geraspte geitenkaas', unit: 'g', amount: 150 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Verwarm de oven voor op 200°C. Snijd de gekookte rode bieten in dunne plakjes en dep goed droog.', timer_seconds: null },
      { id: 's2', content: 'Rooster de pompoenlasagnevellen 10-15 minuten in de oven tot ze net zacht zijn.', timer_seconds: 900 },
      { id: 's3', content: 'Meng mascarpone met melk, fijngesneden salie, peper en zout. Verwarm op laag vuur tot een gladde saus.', timer_seconds: null },
      { id: 's4', content: 'Laag op in een ovenschaal: saus, lasagnebladen, pompoen, bieten, saus en geitenkaas. Herhaal nog 2 keer.', timer_seconds: null },
      { id: 's5', content: 'Bak 45 minuten tot goudbruin. Laat 15-20 minuten rusten vóór het aansnijden.', timer_seconds: 2700 },
    ] }],
    variants: [
      { id: 'var-bolognese', label: 'Klassieke bolognese', steps: [{ group: 'Bereiding', items: [
        { id: 'sv1', content: 'Fruit ui, knoflook, wortel en selderij. Voeg gehakt toe en bak rul. Voeg tomatenblokjes en puree toe, laat 25 min pruttelen. Maak bechamelsaus. Laag op en bak 40-45 min op 200°C.', timer_seconds: 2700 },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi1', name: 'rundergehakt', unit: 'g', amount: 500 },
        { id: 'vi2', name: 'ui, wortel, selderij', unit: null, amount: null },
        { id: 'vi3', name: 'tomatenblokjes', unit: 'g', amount: 800 },
        { id: 'vi4', name: 'lasagnebladen', unit: 'g', amount: 250 },
        { id: 'vi5', name: 'melk', unit: 'ml', amount: 500 },
        { id: 'vi6', name: 'geraspte Parmezaanse kaas', unit: 'g', amount: 100 },
      ] }] },
    ],
    notes: 'Make-ahead/freeze: Excellent freezer candidate, baked or unbaked. Assemble, wrap tightly and freeze up to 3 months.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312360289.jpg',
    calories: 2256, protein_g: 77.5, carbs_g: 160.0, fat_g: 147.1, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(48),
  },
  {
    id: 'demo-naanbrood', title: 'Naanbrood', tagline: 'Om mee te dippen',
    category: 'Sides', subcategory: 'Bread & Dough', servings: 4, total_minutes: 25,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'roeryoghurt', unit: 'ml', amount: 200 },
      { id: 'i2', name: 'olie', unit: 'el', amount: 1 },
      { id: 'i3', name: 'zelfrijzend bakmeel', unit: 'g', amount: 270 },
      { id: 'i4', name: 'snuf zout', unit: null, amount: null },
      { id: 'i5', name: 'verse peterselie', unit: null, amount: null },
      { id: 'i6', name: 'knoflook', unit: 'teen', amount: 1 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Zeef het zelfrijzend bakmeel en voeg samen met de yoghurt, zout, geperste knoflook, 1 el olie en gehakte peterselie toe in een kom. Kneed ongeveer 3 minuten.', timer_seconds: null },
      { id: 's2', content: 'Verdeel het deeg in 4 porties en rol ze uit met een deegroller.', timer_seconds: null },
      { id: 's3', content: 'Verhit een grillpan of koekenpan zonder olie op middelhoog vuur. Bak het deeg ongeveer 2 minuten per kant. Bestrijk na het bakken met een beetje extra olie.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Both the raw dough and cooked naan freeze well for up to 2 months. Reheat cooked naan briefly in a hot dry pan.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313298010.jpg',
    calories: 126, protein_g: 8.3, carbs_g: 11.3, fat_g: 6.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(35),
  },
  {
    id: 'demo-okonomiyaki', title: 'Okonomiyaki', tagline: 'Hartige Japanse pannenkoek',
    category: 'Breakfast & Brunch', subcategory: null, servings: 2, total_minutes: 20,
    ingredients: [
      { group: 'Voor de okonomiyaki saus', items: [
        { id: 'i1', name: 'tomatenketchup', unit: 'el', amount: 4 },
        { id: 'i2', name: 'worcestershiresaus', unit: 'el', amount: 0.5 },
        { id: 'i3', name: 'mirin', unit: 'el', amount: 2 },
        { id: 'i4', name: 'suiker', unit: 'el', amount: 1 },
        { id: 'i5', name: 'lichte sojasaus', unit: 'tl', amount: 1 },
      ] },
      { group: 'Voor de okonomiyaki', items: [
        { id: 'i6', name: 'bloem', unit: 'g', amount: 100 },
        { id: 'i7', name: 'dashi of bouillon', unit: 'ml', amount: 100 },
        { id: 'i8', name: 'eieren', unit: null, amount: 2 },
        { id: 'i9', name: 'panko', unit: 'el', amount: 1 },
        { id: 'i10', name: 'lente-uitjes, in ringetjes gesneden', unit: null, amount: 3 },
        { id: 'i11', name: 'kool, gesnipperd', unit: 'g', amount: 150 },
        { id: 'i12', name: 'plakjes dik ontbijtspek', unit: null, amount: 4 },
        { id: 'i13', name: 'Japanse kewpie mayonaise', unit: null, amount: null },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Klop de eieren los en voeg de bloem en bouillon toe. Roer de kool en gesnipperde bosui erdoorheen en voeg een snufje zout toe. Voeg de panko toe.', timer_seconds: null },
      { id: 's2', content: 'Verhit een koekenpan op middelhoog vuur met zonnebloemolie. Giet het beslag in de pan. Leg de plakjes bacon er bovenop en dek de pan af met een deksel. Bak 3 minuten tot goudbruin.', timer_seconds: 180 },
      { id: 's3', content: 'Keer de okonomiyaki om en laat nog 3 minuten bakken. Verdeel de okonomiyaki saus en mayonaise erover. Maak af met bosui.', timer_seconds: 180 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Freezes well — cool, wrap individually, reheat in a hot pan or oven to re-crisp the edges.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313564533.jpg',
    calories: 1198, protein_g: 28.5, carbs_g: 15.5, fat_g: 113.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(42),
  },
  {
    id: 'demo-couscous', title: 'Parelcouscoussalade', tagline: 'Met geroosterde groenten, feta en krokante serranoham',
    category: 'Main dishes', subcategory: null, servings: 4, total_minutes: 35,
    ingredients: [
      { group: null, items: [
        { id: 'i1', name: 'parelcouscous', unit: 'g', amount: 250 },
        { id: 'i2', name: 'rode ui, in parten', unit: null, amount: 1 },
        { id: 'i3', name: 'broccoli, in roosjes', unit: null, amount: 1 },
        { id: 'i4', name: 'venkel, in dunne parten', unit: null, amount: 1 },
        { id: 'i5', name: 'plakjes serranoham', unit: null, amount: 4 },
        { id: 'i6', name: 'Handje amandelen', unit: null, amount: null },
        { id: 'i7', name: 'feta', unit: 'g', amount: 100 },
      ] },
      { group: 'Voor de dressing', items: [
        { id: 'i8', name: 'extra vergine olijfolie', unit: 'el', amount: 3 },
        { id: 'i9', name: 'Sap van ½ citroen', unit: null, amount: null },
        { id: 'i10', name: 'Dijonmosterd', unit: 'tl', amount: 1 },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Verwarm de oven voor op 180°C. Meng de rode ui, broccoli en venkel met olijfolie, kruiden, zout en peper. Rooster 20 minuten in de oven. Voeg de laatste 8 minuten de amandelen toe.', timer_seconds: 1200 },
      { id: 's2', content: 'Kook ondertussen de parelcouscous in ruim gezouten water. Giet af.', timer_seconds: null },
      { id: 's3', content: 'Meng olijfolie, citroensap en mosterd tot een dressing. Meng de warme couscous met de geroosterde groenten en de dressing. Laat afkoelen.', timer_seconds: null },
      { id: 's4', content: 'Verkruimel feta over de salade. Scheur de serranoham in stukjes en verdeel erover.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Variatie: vervang serranoham door 200g halloumi voor vegetarisch.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313171932.jpg',
    calories: 472, protein_g: 3.2, carbs_g: 16.5, fat_g: 45.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(38),
  },
  {
    id: 'demo-pastachorizo', title: 'Pasta met Chorizo', tagline: 'Chorizo and a lot of cheese!',
    category: 'Main dishes', subcategory: 'Pasta', servings: 4, total_minutes: 30,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'Pasta naar keuze', unit: null, amount: null },
      { id: 'i2', name: 'grote bol mozzarella', unit: null, amount: 1 },
      { id: 'i3', name: 'cheddar kaas', unit: 'zak', amount: 1 },
      { id: 'i4', name: 'chorizo pikant', unit: null, amount: 1 },
      { id: 'i5', name: 'tomatenpuree', unit: 'el', amount: 1 },
      { id: 'i6', name: 'tomatenblokjes', unit: 'blik', amount: 1 },
      { id: 'i7', name: 'witte ui', unit: null, amount: 1 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Kook de pasta. Snipper de ui en snij de chorizo.', timer_seconds: null },
      { id: 's2', content: 'Fruit de ui tot glazig, voeg chorizo en tomatenpuree toe. Bak de groentes mee. Voeg tomatenblokjes toe en laat pruttelen.', timer_seconds: null },
      { id: 's3', content: 'Voeg de cheddar en mozzarella toe totdat het een saus is geworden.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: The chorizo-tomato-cheese sauce freezes well up to 3 months. Cook fresh pasta when serving.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312197820.jpg',
    calories: 1126, protein_g: 72.0, carbs_g: 16.1, fat_g: 86.6, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(22),
  },
  {
    id: 'demo-pitaoesterzwam', title: 'Pita met pulled oesterzwam', tagline: 'En feta en rode ui-pickle',
    category: 'Main dishes', subcategory: null, servings: 4, total_minutes: 40,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'volkoren pitas', unit: 'stuk', amount: 8 },
      { id: 'i2', name: 'veldsla', unit: 'g', amount: 150 },
      { id: 'i3', name: 'rode ui', unit: 'stuk', amount: 1 },
      { id: 'i4', name: 'feta', unit: 'g', amount: 150 },
      { id: 'i5', name: 'oesterzwammen', unit: 'g', amount: 450 },
      { id: 'i6', name: 'shoarmakruiden', unit: 'el', amount: 1 },
      { id: 'i7', name: 'zoete puntpaprikas', unit: 'stuk', amount: 2 },
      { id: 'i8', name: 'Griekse yoghurt', unit: 'g', amount: 200 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Los 50 g suiker en 50 ml witte azijn in een steelpannetje op. Schenk bij de rode ui en laat 15 minuten trekken.', timer_seconds: 900 },
      { id: 's2', content: 'Trek de oesterzwammen in reepjes. Meng met shoarmakruiden en olijfolie. Rooster 15 minuten in de oven op 200°C.', timer_seconds: 900 },
      { id: 's3', content: 'Verkruimel de feta boven een kom en meng met de Griekse yoghurt. Vul de pitas met oesterzwammen, paprika, veldsla, feta-yoghurtsaus en rode ui pickle.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: The roasted oesterzwam and pepper filling freezes well for up to 2 months.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312923329.webp',
    calories: 1211, protein_g: 45.0, carbs_g: 212.0, fat_g: 18.8, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(28),
  },
  {
    id: 'demo-pompoencurry', title: 'Pompoencurry met kikkererwten', tagline: 'Lactose en glutenvrij',
    category: 'Main dishes', subcategory: 'Curry', servings: 4, total_minutes: 45,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'middelgrote pompoen', unit: null, amount: 1 },
      { id: 'i2', name: 'tomatenblokjes uit blik', unit: 'g', amount: 400 },
      { id: 'i3', name: 'kikkererwten uit blik', unit: 'g', amount: 400 },
      { id: 'i4', name: 'kokosmelk', unit: 'ml', amount: 400 },
      { id: 'i5', name: 'ui', unit: null, amount: 1 },
      { id: 'i6', name: 'cm gember', unit: null, amount: 3 },
      { id: 'i7', name: 'knoflook', unit: 'teen', amount: 2 },
      { id: 'i8', name: 'kerriepoeder', unit: 'el', amount: 1 },
      { id: 'i9', name: 'verse koriander', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Snipper de ui. Hak de knoflook en de gember fijn. Snijd de pompoen in stukken van ca 3 cm.', timer_seconds: null },
      { id: 's2', content: 'Verhit in een wok wat zonnebloemolie. Fruit hierin de ui, knoflook en gember. Voeg het kerriepoeder en de pompoen toe en bak een paar minuten mee.', timer_seconds: null },
      { id: 's3', content: 'Voeg de tomatenblokjes en de kokosmelk toe en laat 20-30 minuten op zacht vuur gaar worden.', timer_seconds: 1500 },
      { id: 's4', content: 'Voeg de kikkererwten toe en laat nog 2 minuten meekoken. Dien op en garneer met verse koriander.', timer_seconds: 120 },
    ] }],
    variants: [], notes: 'Tip: serveer met naanbrood of flatbread.\n\nMake-ahead/freeze: Freezes very well for up to 3 months.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312687190.jpg',
    calories: 1588, protein_g: 45.3, carbs_g: 134.6, fat_g: 106.4, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(80),
  },
  {
    id: 'demo-pulledbbq', title: "Pulled BBQ chicken taco's met avocado en mango salade", tagline: "Pulled chicken taco's",
    category: 'Main dishes', subcategory: 'Tacos, wraps & nachos', servings: 4, total_minutes: 40,
    ingredients: [
      { group: null, items: [
        { id: 'i1', name: 'tacoschelpen', unit: null, amount: 8 },
        { id: 'i2', name: 'mais groot', unit: 'blik', amount: 1 },
        { id: 'i3', name: 'paprika\'s', unit: null, amount: 2 },
        { id: 'i4', name: 'kipfilet', unit: 'g', amount: 350 },
        { id: 'i5', name: 'BBQ saus', unit: null, amount: null },
        { id: 'i6', name: 'uien', unit: null, amount: 2 },
        { id: 'i7', name: 'knoflooktenen', unit: null, amount: 3 },
      ] },
      { group: 'Salsa', items: [
        { id: 'i8', name: 'mango', unit: null, amount: 1 },
        { id: 'i9', name: 'avocado', unit: null, amount: 2 },
        { id: 'i10', name: 'limoen', unit: null, amount: 1 },
        { id: 'i11', name: 'feta', unit: 'g', amount: 100 },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: "Doe de kipfilet's in een pan met kokend water en kook ze voor 20 minuten.", timer_seconds: 1200 },
      { id: 's2', content: 'Snijd de mango, avocado in blokjes. Sprenkel er het sap van een halve limoen over met wat peper en zout.', timer_seconds: null },
      { id: 's3', content: 'Snijd de paprika en ui in stukjes. Hak de knoflooktenen klein. Fruit dit samen in een pan.', timer_seconds: null },
      { id: 's4', content: 'Haal de kip uit de pan en trek het uit elkaar met twee vorken. Doe het bij in de pan met groenten en meng de BBQ saus erdoor.', timer_seconds: null },
      { id: 's5', content: 'Verwarm de tacoschelpen 5 minuten op 180°C. Vul ze met het kip-groentenmengsel en serveer met de mango-avocadosalade.', timer_seconds: 300 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: The pulled BBQ chicken freezes great for up to 3 months. Make the mango-avocado salsa fresh each time.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312657781.jpg',
    calories: 1008, protein_g: 121.6, carbs_g: 67.5, fat_g: 27.6, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(15),
  },
  {
    id: 'demo-quiche', title: 'Quiche lorraine', tagline: 'De Franse klassieker',
    category: 'Main dishes', subcategory: 'Oven dishes', servings: 6, total_minutes: 60,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'plakken deeg voor hartige taart', unit: null, amount: 6 },
      { id: 'i2', name: 'eieren', unit: null, amount: 5.5 },
      { id: 'i3', name: 'spekjes', unit: 'g', amount: 275 },
      { id: 'i4', name: 'geraspte kaas (gruyère of goedkope)', unit: 'g', amount: 200 },
      { id: 'i5', name: 'slagroom of crème fraîche', unit: 'ml', amount: 200 },
      { id: 'i6', name: 'middelgrote uien', unit: null, amount: 2 },
      { id: 'i7', name: 'Italiaanse kruiden, basilicum, oregano, knoflook', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Vet je quichevorm in en laat het bladerdeeg ontdooien. Bak de spekjes en snijd de uien. Voeg de uien toe en bak tot het er goed uitziet.', timer_seconds: null },
      { id: 's2', content: 'Beleg je quichevorm en prik met een vork gaatjes in het deeg.', timer_seconds: null },
      { id: 's3', content: 'Voeg de slagroom, kaas, eieren en kruiden bij elkaar in een kom en mix met een garde. Giet het spek-ui mengsel op het deeg, dan het eimengsel erover.', timer_seconds: null },
      { id: 's4', content: 'Zet op 200 graden in de oven, eerst 30 minuten met aluminiumfolie en dan 15 minuten zonder.', timer_seconds: 2700 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Freezes well, baked, for up to 2 months.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312324055.jpg',
    calories: 2615, protein_g: 95.7, carbs_g: 25.1, fat_g: 238.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: ['freezes well'], created_at: day(52),
  },
  {
    id: 'demo-rabokki', title: 'Rabokki', tagline: 'Korean sweet & spicy ramen noodles',
    category: 'Main dishes', subcategory: null, servings: 2, total_minutes: 25,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'Korean stock (or 3 cups chicken stock + 1 cup water)', unit: 'cups', amount: 4 },
      { id: 'i2', name: 'gochujang', unit: 'tbsp', amount: 3 },
      { id: 'i3', name: 'soy sauce', unit: 'tbsp', amount: 2 },
      { id: 'i4', name: 'sugar', unit: 'tbsp', amount: 2 },
      { id: 'i5', name: 'fish cake, cut into bite-size', unit: 'oz', amount: 6 },
      { id: 'i6', name: 'cabbage, sliced', unit: 'oz', amount: 6 },
      { id: 'i7', name: 'green onions, sliced', unit: null, amount: 2 },
      { id: 'i8', name: 'package Korean instant ramen noodles', unit: null, amount: 1 },
      { id: 'i9', name: 'hard-boiled eggs', unit: null, amount: 2 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'In a pot, pour in the stock and add gochujang, soy sauce, and sugar. Stir well and bring to a boil.', timer_seconds: null },
      { id: 's2', content: 'Add the fish cake, cabbage and green onions. Boil for 2-3 minutes.', timer_seconds: null },
      { id: 's3', content: 'Add the noodles and hard-boiled eggs, cook to your liking. Serve garnished with sesame seeds.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: The spicy broth freezes well up to 3 months. Add fresh noodles, fish cake and eggs when reheating.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313137278.jpg',
    calories: 2117, protein_g: 261.7, carbs_g: 45.3, fat_g: 97.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(18),
  },
  {
    id: 'demo-kokosrijst', title: 'Rijst gestoomd in kokosmelk', tagline: 'Hierna wil je niet anders meer',
    category: 'Sides', subcategory: 'Rice & Grains', servings: 4, total_minutes: 40,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'kokosmelk', unit: 'ml', amount: 600 },
      { id: 'i2', name: 'laurierbladen', unit: null, amount: 2 },
      { id: 'i3', name: 'citroengras, gekneusd', unit: 'stengel', amount: 1 },
      { id: 'i4', name: 'kaneelstokjes', unit: null, amount: 2 },
      { id: 'i5', name: 'kruidnagels', unit: null, amount: 2 },
      { id: 'i6', name: 'cm gember', unit: null, amount: 2 },
      { id: 'i7', name: 'nootmuskaat', unit: 'tl', amount: 1 },
      { id: 'i8', name: 'rijst', unit: 'g', amount: 400 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Verhit de kokosmelk in een steelpan op middelhoog vuur.', timer_seconds: null },
      { id: 's2', content: 'Voeg pandanblad, citroengras, laurierblad en kaneelstokjes toe. Voeg de rijst toe en roer goed door. Kook de rijst totdat alle kokosmelk is opgenomen.', timer_seconds: null },
      { id: 's3', content: 'Zet de pan weg met de deksel erop voor 20-30 minuten.', timer_seconds: 1500 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Freezes well for up to 1 month. Reheat with a splash of water or extra coconut milk.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313520053.jpg',
    calories: 2094, protein_g: 24.6, carbs_g: 198.0, fat_g: 145.2, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(32),
  },
  {
    id: 'demo-tagliatellezalm', title: 'Romige tagliatelle met zalm', tagline: 'Gewoon omdat het kan',
    category: 'Main dishes', subcategory: 'Pasta', servings: 4, total_minutes: 30,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'verse tagliatelle', unit: 'g', amount: 500 },
      { id: 'i2', name: 'zalmfilet', unit: null, amount: 1 },
      { id: 'i3', name: 'knoflook', unit: 'teen', amount: 4 },
      { id: 'i4', name: 'roomsaus + benodigdheden', unit: 'pak', amount: 1 },
      { id: 'i5', name: 'gedroogde chilivlokken', unit: 'tl', amount: 1 },
      { id: 'i6', name: 'zongedroogde tomaten', unit: null, amount: 6 },
      { id: 'i7', name: 'courgette', unit: null, amount: 1 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Kook de tagliatelle. Dep de zalmfilets droog en bestrooi met zout en peper. Bak 5 minuten op medium hoog vuur, draai om en bak nog 3 minuten.', timer_seconds: null },
      { id: 's2', content: 'Haal de zalm uit de pan. Bak in dezelfde pan de knoflook samen met de tomaten, courgette en chilivlokken. Blus af met de kookroom.', timer_seconds: null },
      { id: 's3', content: 'Leg de zalmfilets in de saus en laat nog een minuut doorwarmen.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Not a great freezer candidate — cooked salmon turns dry/mushy on reheating. Best made fresh.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312116322.jpg',
    calories: 2083, protein_g: 41.6, carbs_g: 139.3, fat_g: 152.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(12),
  },
  {
    id: 'demo-sandwich', title: 'Sandwich combinaties', tagline: 'Van Broodje Ben',
    category: 'Breakfast & Brunch', subcategory: null, servings: null, total_minutes: null,
    ingredients: [{ group: 'Combinatie ideeën', items: [
      { id: 'i1', name: 'Broodje x gezond (wortel, kaas, sla, tomaat, ei, komkommer)', unit: null, amount: null },
      { id: 'i2', name: 'Vlees: beenham, filet american en rode ui, rosbief, ossenworst of gerookte kip', unit: null, amount: null },
      { id: 'i3', name: 'Vis: tonijn en rode/dille mayonaise', unit: null, amount: null },
      { id: 'i4', name: 'Broodje gerookte kip kerriemayonaise (gerookte kip, kerriemayonaise, rucola, pijnboompitten en mango)', unit: null, amount: null },
      { id: 'i5', name: 'Broodje parmaham oude kaas (parmaham, oude kaas, pesto, rucola, pijnboompitten en zontomaat)', unit: null, amount: null },
      { id: 'i6', name: 'Broodje carpaccio/runderpastrami truffelmayonaise (carpaccio/pastrami, truffelmayonaise, pesto, rucola, parmezaanse kaas)', unit: null, amount: null },
      { id: 'i7', name: 'Broodje gerookte zalm kruidenkaas (gerookte zalm, kruidenkaas, rucola, rode ui en tomaat)', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Kies een combinatie. Besmeer het broodje met de saus. Begin met een laag sla of rucola, leg het vlees, vis of vulling erop, en eindig met de overige toppings.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Lijst met sandwichcombinaties, geen vast recept met stappen.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313662768.png',
    calories: 1874, protein_g: 135.7, carbs_g: 218.9, fat_g: 128.5, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(25),
  },
  {
    id: 'demo-soup', title: 'Sausage potato soup', tagline: 'Heel veel cream',
    category: 'Soups & Salads', subcategory: null, servings: 6, total_minutes: 45,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'Italian sausage, mild or hot', unit: 'g', amount: 906 },
      { id: 'i2', name: 'unsalted butter, divided', unit: 'g', amount: 140 },
      { id: 'i3', name: 'diced carrots', unit: 'cup', amount: 0.75 },
      { id: 'i4', name: 'diced celery', unit: 'cup', amount: 0.75 },
      { id: 'i5', name: 'chopped baby gold potatoes', unit: 'g', amount: 1272 },
      { id: 'i6', name: 'chicken stock', unit: 'g', amount: 1992 },
      { id: 'i7', name: 'milk', unit: 'g', amount: 1416 },
      { id: 'i8', name: 'heavy cream', unit: 'g', amount: 240 },
      { id: 'i9', name: 'freshly shredded extra-sharp cheddar cheese', unit: 'g', amount: 940 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Add sausage, sear briefly, then crumble and cook until browned.', timer_seconds: null },
      { id: 's2', content: 'Melt butter in the pot. Add carrots, celery, and onion; sauté until softened.', timer_seconds: null },
      { id: 's3', content: 'Stir in potatoes and chicken stock, bring to a boil, then simmer 15–20 minutes.', timer_seconds: 1200 },
      { id: 's4', content: 'Make a roux with butter and flour, whisk in milk until thickened, stir in cream.', timer_seconds: null },
      { id: 's5', content: 'Combine with the soup, add cheese gradually, stirring until melted. Serve warm.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Storage: fridge 3-4 days airtight, or freeze flat in a freezer bag.',
    photo_url: null,
    calories: 13699, protein_g: 963.1, carbs_g: 263.1, fat_g: 972.3, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: ['nice cold'], created_at: day(20),
  },
  {
    id: 'demo-shakshuka', title: 'Shakshuka', tagline: 'Waar het ook vandaan komt',
    category: 'Main dishes', subcategory: null, servings: 3, total_minutes: 30,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'ui', unit: null, amount: 1 },
      { id: 'i2', name: 'knoflookteentje', unit: null, amount: 1 },
      { id: 'i3', name: 'rode paprika', unit: null, amount: 1 },
      { id: 'i4', name: 'tomatenpuree', unit: 'el', amount: 1 },
      { id: 'i5', name: 'tomatenblokjes', unit: 'g', amount: 400 },
      { id: 'i6', name: 'cayennepeper', unit: 'tl', amount: 1 },
      { id: 'i7', name: 'eieren', unit: null, amount: 3 },
      { id: 'i8', name: 'brood om mee te dippen', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Snipper de ui en de knoflook fijn. Verhit olijfolie in een diepe koekenpan en fruit de ui.', timer_seconds: null },
      { id: 's2', content: 'Snijd de paprika in stukjes en voeg samen met de knoflook toe. Voeg de tomatenpuree en tomatenblokjes toe, zet het vuur laag. Voeg kruiden toe.', timer_seconds: null },
      { id: 's3', content: 'Maak een kuiltje in je saus per eitje. Leg een deksel op je pan en laat de eieren in 6-8 minuten pocheren. Serveer in de pan.', timer_seconds: 480 },
    ] }],
    variants: [], notes: 'Kruiden classic: komijnzaad, chilipoeder en paprikapoeder.\n\nMake-ahead/freeze: The tomato-paprika sauce base freezes very well up to 3 months. Poach fresh eggs in the reheated sauce each time.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312829491.jpg',
    calories: 223, protein_g: 8.2, carbs_g: 44.0, fat_g: 1.6, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(8),
  },
  {
    id: 'demo-spanakopita', title: 'Spanakopita', tagline: 'Griekse spinazietaart met filodeeg',
    category: 'Appetizers & Snacks', subcategory: null, servings: null, total_minutes: null,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'vellen filodeeg, ontdooid', unit: null, amount: 6 },
      { id: 'i2', name: 'verse of diepgevroren spinazie', unit: 'kg', amount: 1 },
      { id: 'i3', name: 'feta, verkruimeld', unit: 'g', amount: 350 },
      { id: 'i4', name: 'eieren, los geklutst', unit: null, amount: 2 },
      { id: 'i5', name: 'Zout & peper, naar smaak', unit: null, amount: null },
      { id: 'i6', name: 'Dille, naar smaak', unit: null, amount: null },
      { id: 'i7', name: 'Olijfolie', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Haal het filodeeg uit de vriezer en bewaar tot je het gebruikt onder een vochtige theedoek. Verwarm de oven voor op 200 graden.', timer_seconds: null },
      { id: 's2', content: 'Bak de spinazie tot het mooi geslonken is en knijp al het vocht eruit. Snij de spinazie grof en meng met de feta, dille en 2 geklutste eieren. Breng op smaak met zout en peper.', timer_seconds: null },
      { id: 's3', content: 'Bekleed een ingevette ovenschaal met vellen filodeeg, bestrijk elke laag met olijfolie.', timer_seconds: null },
      { id: 's4', content: 'Verdeel het spinaziemengsel eroverheen en strijk dit mooi plat. Maak af met nog 3 vellen filodeeg.', timer_seconds: null },
      { id: 's5', content: 'Bak ongeveer 20 minuten, totdat het filodeeg goudbruin is.', timer_seconds: 1200 },
    ] }],
    variants: [], notes: 'Freezes well both ways: unbaked (wrap tightly, bake from frozen adding 5-10 min) or baked (cool, wrap, freeze up to 1 month).',
    photo_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Spanakopita.jpg',
    calories: 1572, protein_g: 50.0, carbs_g: 186.0, fat_g: 74.0, nutrition_is_estimate: true,
    wishlist: true, freezer_friendly: true, tags: ['freezes well'], created_at: day(95),
  },
  {
    id: 'demo-ramenbowl', title: 'Snelle ramenbowl', tagline: 'Voor als er snel wat eten in moet',
    category: 'Main dishes', subcategory: 'Ramen', servings: 4, total_minutes: 25,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'eieren', unit: 'stuk', amount: 4 },
      { id: 'i2', name: 'woknoedels', unit: 'pak', amount: 1 },
      { id: 'i3', name: 'kokosmelk', unit: 'el', amount: 4 },
      { id: 'i4', name: 'rode currypasta', unit: 'el', amount: 2 },
      { id: 'i5', name: 'cm gember', unit: null, amount: 2 },
      { id: 'i6', name: 'zwart sesamzaad', unit: 'el', amount: 2 },
      { id: 'i7', name: 'shiitake', unit: 'g', amount: 100 },
      { id: 'i8', name: 'bosui', unit: 'stengel', amount: 2 },
      { id: 'i9', name: 'winterpeen', unit: 'stuk', amount: 1 },
      { id: 'i10', name: 'groentebouillon', unit: 'l', amount: 2 },
      { id: 'i11', name: 'sojasaus', unit: 'el', amount: 2 },
      { id: 'i12', name: 'knoflook', unit: 'teen', amount: 2 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Schil en rasp 2 cm gember en pers 2 teentjes knoflook. Verhit 2 el olie, fruit de gember en knoflook. Voeg de shiitake toe en fruit kort mee.', timer_seconds: null },
      { id: 's2', content: 'Maak 2 liter groentebouillon. Voeg rode currypasta, sojasaus, kokosmelk en alle bouillon toe. Breng aan de kook.', timer_seconds: null },
      { id: 's3', content: 'Voeg de woknoedels toe en laat 5-6 minuten koken. Kook ondertussen 4 eieren 6-7 minuten.', timer_seconds: 360 },
      { id: 's4', content: 'Rasp de winterpeen en voeg toe. Verdeel de soep over de kommen, leg twee halve eitjes in elke kom. Garneer met bosui en sesamzaadjes.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Extra lekker met wat crispy chili-olie.\n\nMake-ahead/freeze: The broth (without noodles or eggs) freezes well up to 3 months.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312782936.jpg',
    calories: 799, protein_g: 14.6, carbs_g: 76.2, fat_g: 49.7, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: true, tags: [], created_at: day(5),
  },
  {
    id: 'demo-wintercocktail', title: 'Spiced winter cocktail', tagline: 'To make a big batch',
    category: 'Drinks', subcategory: 'Cocktails', servings: 8, total_minutes: 20,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'cranberrysap (voor siroop)', unit: 'ml', amount: 250 },
      { id: 'i2', name: 'sinaasappelrasp', unit: null, amount: null },
      { id: 'i3', name: 'steranijs', unit: null, amount: 1 },
      { id: 'i4', name: 'kaneelstokjes', unit: null, amount: 2 },
      { id: 'i5', name: 'bruine suiker', unit: 'el', amount: 3 },
      { id: 'i6', name: 'fles prosecco', unit: null, amount: 1 },
      { id: 'i7', name: 'ginger ale', unit: 'ml', amount: 50 },
      { id: 'i8', name: 'cranberrysap', unit: 'ml', amount: 500 },
      { id: 'i9', name: 'spiced rum', unit: 'ml', amount: 120 },
      { id: 'i10', name: 'sinaasappelschijfjes en verse cranberries', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Maak de siroop: cranberrysap, sinaasappelrasp, steranijs, kaneelstokjes en suiker samen laten inkoken voor 10 minuten.', timer_seconds: 600 },
      { id: 's2', content: 'Giet de prosecco, ginger ale, cranberrysap en spiced rum in de drankdispenser.', timer_seconds: null },
      { id: 's3', content: 'Haal het mengsel door een zeef en laat de siroop afkoelen. Voeg de afgekoelde siroop, sinaasappelschijfjes en cranberries toe.', timer_seconds: null },
      { id: 's4', content: 'Dip het randje van het glas door honing en dan bruine suiker. Vul het glas en garneer met sinaasappelschil, cranberries en een kaneelstokje.', timer_seconds: null },
    ] }],
    variants: [
      { id: 'var-mocktail', label: 'Alcoholvrije versie', steps: [{ group: 'Bereiding', items: [
        { id: 'sv1', content: 'Maak de siroop op dezelfde manier. Vervang de prosecco en rum door bruisend water en sinaasappelsap. Gebruik ginger ale voor de smaak.', timer_seconds: null },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi1', name: 'bruisend water of alcoholvrije bubbels', unit: 'ml', amount: 750 },
        { id: 'vi2', name: 'ginger ale', unit: 'ml', amount: 50 },
        { id: 'vi3', name: 'cranberrysap', unit: 'ml', amount: 500 },
        { id: 'vi4', name: 'sinaasappelsap', unit: 'ml', amount: 120 },
      ] }] },
    ],
    notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313746943.jpg',
    calories: 312, protein_g: 0.1, carbs_g: 81.4, fat_g: 0.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: ['Cold Meal'], created_at: day(115),
  },
  {
    id: 'demo-springrolls', title: 'Spring rolls', tagline: 'Fresh and lovely',
    category: 'Main dishes', subcategory: null, servings: 4, total_minutes: 30,
    ingredients: [
      { group: null, items: [
        { id: 'i1', name: 'Spring roll wrappers', unit: null, amount: null },
      ] },
      { group: 'Opties voor de vulling', items: [
        { id: 'i2', name: 'Komkommer', unit: null, amount: null },
        { id: 'i3', name: 'Radijs', unit: null, amount: null },
        { id: 'i4', name: 'Wortel julienne', unit: null, amount: null },
        { id: 'i5', name: 'Imitatie krab / garnalen / zalm vlokken', unit: null, amount: null },
        { id: 'i6', name: 'IJsberg sla', unit: null, amount: null },
        { id: 'i7', name: 'Verse koriander (+ munt)', unit: null, amount: null },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Zorg dat er een klein laagje warm water in een pan ligt. Leg de wrappings er kort in zodat alles ondergedompeld ligt. Leg dan op een vlakke ondergrond.', timer_seconds: null },
      { id: 's2', content: 'Voeg zoveel vulling toe als je wil maar zorg dat je het kan dichtrollen. Vouw eerst de zijkanten dicht, dan de rest oprollen.', timer_seconds: null },
      { id: 's3', content: 'Serveer met een dipsaus. Voor meenemen als lunch: doe er bakpapier tussen en bewaar koud.', timer_seconds: null },
    ] }],
    variants: [
      { id: 'var-hoisin', label: 'Hoisin dipsaus', steps: [{ group: 'Bereiding', items: [
        { id: 'sv1', content: 'Klop alle ingrediënten samen tot een gladde dipsaus: hoisin sauce, sesame oil, chili oil en water.', timer_seconds: null },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi1', name: 'hoisin sauce', unit: 'tbsp', amount: 2 },
        { id: 'vi2', name: 'toasted sesame oil', unit: 'tsp', amount: 2 },
        { id: 'vi3', name: 'chili oil', unit: 'tsp', amount: 2 },
        { id: 'vi4', name: 'water', unit: 'tbsp', amount: 6 },
      ] }] },
    ],
    notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313105697.jpg',
    calories: 265, protein_g: 15.3, carbs_g: 31.3, fat_g: 8.1, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(40),
  },
  {
    id: 'demo-sundried', title: 'Sun dried tomato pasta', tagline: 'Very nice to freeze too!',
    category: 'Main dishes', subcategory: 'Pasta', servings: 3, total_minutes: 25,
    ingredients: [
      { group: 'Creamy Sauce', items: [
        { id: 'i1', name: 'sun dried tomatoes chopped', unit: 'cup', amount: 0.75 },
        { id: 'i2', name: 'basil leaves', unit: 'cup', amount: 0.5 },
        { id: 'i3', name: 'yoghurt or sour cream', unit: 'cup', amount: 0.25 },
        { id: 'i4', name: 'cream', unit: 'cup', amount: 0.25 },
        { id: 'i5', name: '3/4 cups milk', unit: null, amount: 1 },
        { id: 'i6', name: 'tomato paste', unit: 'tbsp', amount: 1 },
        { id: 'i7', name: 'parmesan cheese, finely grated', unit: 'cup', amount: 0.25 },
      ] },
      { group: 'Pasta', items: [
        { id: 'i8', name: 'pasta of choice', unit: 'g', amount: 300 },
        { id: 'i9', name: 'garlic cloves', unit: null, amount: 2 },
        { id: 'i10', name: 'small white onion, finely diced', unit: null, amount: 1 },
        { id: 'i11', name: 'finely shredded fresh spinach', unit: 'cups', amount: 4 },
      ] },
    ],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Place the Creamy Sauce ingredients in a blender and puree until smooth. Adjust salt to taste.', timer_seconds: null },
      { id: 's2', content: 'Heat oil, add garlic (20 seconds), then onion (3-5 minutes until translucent). Cook pasta until al dente, reserve 1 mug of pasta water.', timer_seconds: null },
      { id: 's3', content: 'Add pasta into the skillet with the sauce, spinach and pasta water. Stir to coat and wilt the spinach. Cook 2 minutes until warmed through.', timer_seconds: 120 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Keeps 2 days in the fridge; best reheated gently with a splash of milk.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312223377.jpg',
    calories: 1627, protein_g: 81.0, carbs_g: 157.0, fat_g: 80.6, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(16),
  },
  {
    id: 'demo-thaicurry', title: 'Thai Fish Curry', tagline: "You'll love it!",
    category: 'Main dishes', subcategory: 'Curry', servings: 2, total_minutes: 25,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: '½ lb white fish', unit: null, amount: 1 },
      { id: 'i2', name: 'red Thai curry paste', unit: 'tbsp', amount: 3 },
      { id: 'i3', name: 'coconut oil', unit: 'tbsp', amount: 2 },
      { id: 'i4', name: '½ medium onion', unit: null, amount: null },
      { id: 'i5', name: 'finely minced ginger', unit: 'tbsp', amount: 2 },
      { id: 'i6', name: 'garlic cloves', unit: null, amount: 3 },
      { id: 'i7', name: 'coconut milk', unit: 'oz can', amount: 15 },
      { id: 'i8', name: 'fish sauce', unit: 'tbsp', amount: 1 },
      { id: 'i9', name: 'chopped veggies', unit: 'cups', amount: 4 },
      { id: 'i10', name: 'cilantro and lime juice (to serve)', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Heat the oil in a large pot. Add the onion, ginger, and garlic and cook until golden brown, about 5 minutes.', timer_seconds: null },
      { id: 's2', content: 'Add the curry paste, coconut milk, water, fish sauce, and sugar. Add the veggies and bring to a boil.', timer_seconds: null },
      { id: 's3', content: 'Reduce heat to medium-low and add the fish. Cover and cook for 5 minutes until the fish is no longer opaque. Serve with cilantro and lime juice.', timer_seconds: 300 },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: The curry base (without the fish) freezes well up to 3 months. Cook fresh fish in it when serving.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312718745.jpg',
    calories: 2142, protein_g: 26.9, carbs_g: 144.5, fat_g: 180.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(50),
  },
  {
    id: 'demo-tiramisu', title: 'Tiramisu', tagline: 'Om misselijk van te worden, zo goed',
    category: 'Desserts', subcategory: null, servings: 8, total_minutes: 30,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'eiwit', unit: null, amount: 3 },
      { id: 'i2', name: 'suiker', unit: 'g', amount: 150 },
      { id: 'i3', name: 'eidooiers', unit: null, amount: 3 },
      { id: 'i4', name: 'mascarpone', unit: 'g', amount: 400 },
      { id: 'i5', name: 'lange vingers', unit: 'g', amount: 200 },
      { id: 'i6', name: 'amandellikeur', unit: 'ml', amount: 50 },
      { id: 'i7', name: 'koude koffie', unit: 'ml', amount: 175 },
      { id: 'i8', name: 'pure chocolade', unit: 'g', amount: 200 },
      { id: 'i9', name: 'cacaopoeder', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Klop de eiwitten met de helft van de suiker tot stijve pieken. Klop de eidooiers met de resterende suiker schuimig.', timer_seconds: null },
      { id: 's2', content: 'Roer de mascarpone los en meng de eidooiers erdoor. Spatel het eiwit erdoor. Meng de likeur met de koffie.', timer_seconds: null },
      { id: 's3', content: 'Bedek de bodem van een ovenschaal met lange vingers en bestrijk met het koffiemengsel. Schep de helft van het mascarponemengsel erover en rasp chocolade op.', timer_seconds: null },
      { id: 's4', content: 'Herhaal met een laag lange vingers, chocolade en mascarponemengsel. Laat opstijven in de koelkast. Bestuif voor het serveren met cacaopoeder.', timer_seconds: null },
    ] }],
    variants: [
      { id: 'var-limoncello', label: 'Limoncello', steps: [{ group: 'Bereiding', items: [
        { id: 'sv1', content: 'Klop slagroom stijf. Meng mascarpone en poedersuiker erdoor. Dip lange vingers in limoncello en laag op. Zet 1 uur in de koelkast. Bestrooi met citroenrasp en geroosterde amandelen.', timer_seconds: 3600 },
      ] }], ingredients: [{ group: null, items: [
        { id: 'vi1', name: 'slagroom', unit: 'ml', amount: 200 },
        { id: 'vi2', name: 'mascarpone', unit: 'g', amount: 250 },
        { id: 'vi3', name: 'poedersuiker', unit: 'g', amount: 50 },
        { id: 'vi4', name: 'limoncello', unit: 'ml', amount: 100 },
        { id: 'vi5', name: 'lange vingers', unit: 'g', amount: 100 },
      ] }] },
    ],
    notes: 'Make-ahead/freeze: Best made 1 day ahead. Keeps well covered in the fridge for 2-3 days. Not recommended to freeze.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782313857343.jpg',
    calories: 3471, protein_g: 30.0, carbs_g: 288.0, fat_g: 250.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(40),
  },
  {
    id: 'demo-risotto', title: 'Truffelrisotto', tagline: 'Met gekarameliseerde knolselderij en rucola',
    category: 'Main dishes', subcategory: 'Risottos', servings: 4, total_minutes: 60,
    ingredients: [{ group: null, items: [
      { id: 'i1', name: 'knolselderij', unit: 'g', amount: 600 },
      { id: 'i2', name: 'milde olijfolie', unit: 'el', amount: 3 },
      { id: 'i3', name: 'rucola', unit: 'zak', amount: 1 },
      { id: 'i4', name: 'bospaddenstoelenbouillontablet', unit: null, amount: 1 },
      { id: 'i5', name: 'sjalotten', unit: null, amount: 2 },
      { id: 'i6', name: 'knoflook', unit: 'teen', amount: 2 },
      { id: 'i7', name: 'risottorijst met truffel', unit: 'g', amount: 300 },
      { id: 'i8', name: 'droge witte wijn', unit: 'ml', amount: 125 },
      { id: 'i9', name: 'Parmezaanse kaas', unit: 'g', amount: 100 },
      { id: 'i10', name: 'ongezouten roomboter', unit: 'g', amount: 30 },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Verwarm de oven voor op 200°C. Snijd de knolselderij in blokjes van 1 cm. Rooster ca. 30 min in de oven. Kook het water met het bouillonblokje.', timer_seconds: 1800 },
      { id: 's2', content: 'Snipper de sjalotten en knoflook. Verhit olie in een pan met dikke bodem en fruit 5 min op laag vuur. Voeg risottorijst toe en fruit al roerend 3 min.', timer_seconds: null },
      { id: 's3', content: 'Voeg de wijn toe en roer tot opgenomen. Voeg bouillon soeplepel voor soeplepel toe, roerend tot opgenomen, ca. 20 min.', timer_seconds: 1200 },
      { id: 's4', content: 'Haal de risotto van het vuur en roer de knolselderij, boter en geraspte kaas erdoor. Verdeel over borden met rucola erover.', timer_seconds: null },
    ] }],
    variants: [], notes: 'Make-ahead/freeze: Risotto doesn\'t freeze or reheat well. Best made fresh and eaten right away.',
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312752344.jpg',
    calories: 1282, protein_g: 34.2, carbs_g: 88.8, fat_g: 87.7, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: false, tags: [], created_at: day(44),
  },
  {
    id: 'demo-kipkorn', title: 'Wraps met kipkorn', tagline: 'Omdat het restjes op kan maken',
    category: 'Main dishes', subcategory: 'Tacos, wraps & nachos', servings: 2, total_minutes: 15,
    ingredients: [{ group: 'Per persoon', items: [
      { id: 'i1', name: 'kipcorn / krokante kipburger', unit: 'stuk', amount: 2 },
      { id: 'i2', name: 'beetje ijsbergsla', unit: null, amount: null },
      { id: 'i3', name: 'tomaten', unit: null, amount: 1.5 },
      { id: 'i4', name: 'komkommer', unit: null, amount: 0.25 },
      { id: 'i5', name: 'rode ui (of 2 stengels bosui)', unit: null, amount: 1 },
      { id: 'i6', name: 'honingmosterdsaus', unit: null, amount: null },
    ] }],
    steps: [{ group: 'Bereiding', items: [
      { id: 's1', content: 'Snijd de groenten en sla in reepjes/stukjes.', timer_seconds: null },
      { id: 's2', content: 'Bak de kipcorn/kipburger volgens de aanwijzingen op de verpakking.', timer_seconds: null },
      { id: 's3', content: 'Beleg de wrap met sla, tomaat, komkommer, rode ui en de kip. Voeg een streep honingmosterdsaus toe en rol de wrap dicht.', timer_seconds: null },
    ] }],
    variants: [], notes: null,
    photo_url: 'https://ubphrbaxvqgdmmcaznee.supabase.co/storage/v1/object/public/recipe-photos/35831ab6-68f9-4804-8723-f2a81ec62a10/1782312508305.jpg',
    calories: 354, protein_g: 27.2, carbs_g: 41.5, fat_g: 10.0, nutrition_is_estimate: true,
    wishlist: false, freezer_friendly: null, tags: [], created_at: day(6),
  },
]

// Fabricated cook log entries so Stats has real-looking data to show in guest mode.
export const DEMO_COOK_LOG = [
  { id: 'log1', recipe_id: 'demo-chili', cooked_date: day(8), thumbs: 'up', notes: 'Even lekkerder de volgende dag', variant_label: null },
  { id: 'log2', recipe_id: 'demo-chili', cooked_date: day(35), thumbs: 'up', notes: null, variant_label: null },
  { id: 'log3', recipe_id: 'demo-baobuns', cooked_date: day(25), thumbs: 'up', notes: 'Bloemkool iets langer roosteren', variant_label: null },
  { id: 'log4', recipe_id: 'demo-tiramisu', cooked_date: day(40), thumbs: 'up', notes: null, variant_label: 'Limoncello' },
  { id: 'log5', recipe_id: 'demo-tiramisu', cooked_date: day(70), thumbs: 'up', notes: 'Klassieke versie blijft de favoriet', variant_label: null },
  { id: 'log6', recipe_id: 'demo-bruschetta', cooked_date: day(15), thumbs: 'up', notes: null, variant_label: null },
  { id: 'log7', recipe_id: 'demo-bruschetta', cooked_date: day(60), thumbs: 'down', notes: 'Tomaten waren niet rijp genoeg', variant_label: null },
  { id: 'log8', recipe_id: 'demo-pompoencurry', cooked_date: day(50), thumbs: 'up', notes: null, variant_label: null },
  { id: 'log9', recipe_id: 'demo-spanakopita', cooked_date: day(90), thumbs: 'up', notes: null, variant_label: null },
  { id: 'log10', recipe_id: 'demo-soup', cooked_date: day(18), thumbs: 'up', notes: 'Extra kaas erbij', variant_label: null },
  { id: 'log11', recipe_id: 'demo-shakshuka', cooked_date: day(5), thumbs: 'up', notes: 'Met harissa mix', variant_label: null },
  { id: 'log12', recipe_id: 'demo-kimchirice', cooked_date: day(12), thumbs: 'up', notes: null, variant_label: null },
  { id: 'log13', recipe_id: 'demo-pastachorizo', cooked_date: day(22), thumbs: 'up', notes: 'Extra cheddar toegevoegd', variant_label: null },
  { id: 'log14', recipe_id: 'demo-gyoza', cooked_date: day(32), thumbs: 'up', notes: null, variant_label: 'Smashed gyoza' },
  { id: 'log15', recipe_id: 'demo-ramenbowl', cooked_date: day(3), thumbs: 'up', notes: 'Crispy chili-olie erbij, aanrader!', variant_label: null },
]

export const DEMO_SHOPPING_LIST = []

export const DEMO_MEAL_GROUPS = [
  { id: 'demo-group-1', name: 'Weekend bakdag', notes: 'Twee desserts, één middag', recipe_ids: ['demo-baklava', 'demo-tiramisu'] },
  { id: 'demo-group-2', name: 'Koreaans avondje', notes: null, recipe_ids: ['demo-kimchirice', 'demo-gyoza', 'demo-rabokki'] },
  { id: 'demo-group-3', name: 'Tapas & snacks', notes: null, recipe_ids: ['demo-bruschetta', 'demo-caprese', 'demo-chiliconqueso', 'demo-springrolls'] },
]
